### ISSUE TITLE
Allow Augmentation to Groupings

### ISSUE THREAD

**Issue by xufengliu** [netmod-wg/yang-next#32] opened 2018-01-25 14:50 UTC
During the discussions of TE tunnel and topology models, we have found that
it is desirable to have the capability of augmenting a grouping.

In our case, there are multiple technology specific models augmenting a
base generic model. In the base model, some groupings are used multiple
times, and each augmentation model needs to add more schema nodes to the
grouping structure. For now, we have to specify an “augment” statement for
each location where the grouping is used. Such an “augment” statement is
repeated many times. It would be convenient and cleaner if we could augment
the grouping.

https://mailarchive.ietf.org/arch/search/?email_list=netmod&q=augmentation+to+grouping

**Comment by schoenw** [comment] 2018-07-18 17:16
I think this has been proposed before but is generally non-trivial. What does using a grouping mean if the grouping has been augmented? Does an augmentation of a grouping immediately apply to all uses? I believe this is problematic.

**Comment by immibis** [comment] 2018-07-27 00:35
Obviously augmentation of a grouping should apply to all it uses.

I agree this is non-trivial to implement.

**Comment by rovarga** [comment] 2018-10-15 21:17
i feel this is a duplicate of #51 . As an implementor, I will certainly use the same faculties to implement this -- https://jira.opendaylight.org/browse/YANGTOOLS-575 covers as a work in progress.

**Comment by rovarga** [comment] 2018-10-15 21:20
@schoenw I do not believe application to all uses is *that* problematic. In metamodel terms it boils down to manipulating the declared model before it is transformed to an effective one -- completely doable. It does require some work on model lifecycle, i.e. in NETCONF scope that means that any model which uses this extension needs to be a party to negotiation, similar to what if-feature/deviation is doing today.

**Comment by mbj4668** [comment] 2018-11-01 20:06
@rovarga I don't think this is related to #51.  This is about augmenting a grouping with normal data defintion statements.

**Comment by mbj4668** [comment] 2018-11-01 20:07
I don't think this a good idea.   The problem is that you can't be sure that it is safe to augment *all* uses of a grouping.

**Comment by rovarga** [comment] 2018-11-27 10:34
@mbj4668 I agree that adding data nodes in general is a bad idea, unless you have overall control. However if you are in control of how the groupings are instantiated, as it can save a lot of boiler-plate and hunting down all the places you forgot to add augment.
I would think that groupings which are valid targets of such a mechanism would communicate this via some sort of designator, hence all users of them would be aware that there may be stuff they do not know about.

**Comment by abierman** [comment] 2019-01-22 22:08
Agree this should not be added.
Absolutely need to control which "uses" gets the new additions to the grouping.
Can do that now with new grouping.
What is the use-case?  Why not just update the grouping if every single uses
is supposed to get the additions?

**Comment by kwatsen** [comment] 2019-02-06 15:34
Closed during Feb 6 Virtual Interim meeting.

**Closed as completed by kwatsen** 2019-02-06 15:34 UTC
Labels: complexity-high, backcompat-low, No support
