### ISSUE TITLE
Clarify YANG validation for data nodes 'decoded' from anydata to a tree of real nodes

### ISSUE THREAD

**Issue by abierman** [netmod-wg/yang-next#29] opened 2017-09-30 22:04 UTC
What are the expectations for offline validation of a datastore?
Current YANG operations and actions encode an arbitrary tree of data as anydata or anyxml.
Example:  NETCONF <config> input or <data> output

Seems like an implementation detail for the client to convert the anydata back to objects
so the YANG validation rules for those "real" objects can be checked.

Possible solution:
 - Define an extension or reuse schema mount to declare that rpc/input/config is
really a schema mount for "root"

**Comment by schoenw** [comment] 2018-07-18 17:20
I do not think that rpc input is a schema mount or I do not understand the issue.

**Comment by mbj4668** [comment] 2018-11-01 19:59
I think the issue is edit-config / input / config, which is an anydata/anyxml node.  How does a tool (such as offline validate) know what kind of anydata to expect?  In this case it is nodes from the schema for the requested datastore.
I don't think schema mount is the right solution to this problem.  Also, I'm not sure this is a problem worth solving.

**Comment by kwatsen** [comment] 2019-02-20 15:12
Unclear if needed for a standard.  Tools can do this on their own?

Closed in Virtual Interim on Feb 20.

**Closed as completed by kwatsen** 2019-02-20 15:12 UTC
Labels: complexity-low, importance-low, Not a YANG Issue, Tooling issue
