### ISSUE TITLE
Allow config=true list without a key-stmt

### ISSUE THREAD

**Issue by abierman** [netmod-wg/yang-next#132] opened 2024-08-24 18:31 UTC
There are use-cases where the key is only added to be valid YANG.
It is just overhead.

E.g., the entire list is provided at once within a parent container.
There are no expectations to edit or retrieve specific entries.
The entire list is deleted at once by deleting the parent container.

**Comment by BalazsLengyel** [comment] 2024-10-03 14:24
I don't want this.
Keyless lists are generally a problem. They look nice as long as they are short and not editable. 
Often they become editable later e.g. by a new version or by a deviation.

**Comment by janlindblad** [comment] 2024-10-23 09:45
I agree with Kent, keyless lists are already overused by clueless/forgetful modelers and cause real world headaches and performance issues. If compilers started to accept lists without keys, global YANG module quality would deteriorate.

**Comment by abierman** [comment] 2024-10-23 16:49
Do not agree a keyless config list is lazy or useless.
It is actually keyed by position, not keyless.

One of the things that makes YANG very heavyweight is the insistence that full protocol control is mandatory all the time.

There are workarounds so this is not that important.
E.g, use a custom RPC instead of edit-config, since keyless lists are OK in RPC input.

Most people expect there to be support for "autokey" since that's how modern database APIs work.
They are surprised that YANG mandates semantic keys sometimes

**Comment by kwatsen** [comment] 2024-10-24 14:53
This a duplicate of another issue

**Closed as completed by kwatsen** 2024-10-24 14:53 UTC
