### ISSUE TITLE
allow more restriction on Identity-ref

### ISSUE THREAD

**Issue by lllyfeng** [netmod-wg/yang-next#120] opened 2022-12-13 01:44 UTC
the current identity-ref type only have base statements to indicate the identites dervied from base identity can be acceptable values. But it's not enough.
For example,

If an identity-ref' base is iana-interface-type, but ddnX25 which is dervied from iana-interface-type is not allowed. How to express it?

So, I suggest add 'permit'/'deny' statements to base statement.
Like this:

```
type identity-ref  {              
   base iana:iana-interface-type { 
      permit xxxx; 
      deny xxxx;
   }
}
```

**Comment by abierman** [comment] 2024-08-31 18:48
I do not see why both permit and deny are needed in this case.
What happens for a value in neither list?

This is related to #80 and #107

This sub-statement is applicable if the restriction is applied to every server implementation.

A shorthand form instead of a complex must/when expression would be much easier to use

Must Do: complexity: medium, bc: high, importance: high

**Comment by lllyfeng** [comment] 2024-09-04 09:52
I agree, it should be either permit or deny,:)

**Comment by kwatsen** [comment] 2024-10-03 14:35
Closed because it;s a duplicate of other issues.

**Closed as completed by kwatsen** 2024-10-03 14:35 UTC
